env:
  global:
    - VERSION=0.${TRAVIS_BUILD_NUMBER}
    
sudo: required

addons:
  apt:
    packages:
      - net-tools

script:

  # Init swarm and network, we need 1.13
  - set -e
  - curl -fsSL https://get.docker.com/ | sh
  - docker swarm init --advertise-addr 127.0.0.1
  - docker node ls
  - docker stack deploy --compose-file docker-stack.yml wordpress

  # Capture the VM's IP
  - export MY_IP=`ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1`
  - echo $MY_IP

  # Check the service
  - docker service ls
  - sleep 10

  # Dump logs of first container and scale to 10
  - docker ps
  - export CONTAINER_COUNT=`docker ps -q $1 | wc -l`
  - docker service scale wordpress_wordpress=10

  # Let cluster form w/ 10 nodes and verify there are 10 instance members
  - sleep 30
  - docker ps
  - export CONTAINER_COUNT=`docker ps -q $1 | grep wordpress:php7.1-fpm-alpine | wc -l`
  - echo $CONTAINER_COUNT
  - if [[ "$CONTAINER_COUNT" == 10 ]]; then echo "OK"; else exit 1; fi

  # Scale cluster down to 2 nodes, wait 2 minutes then verify only 3 nodes
  - docker service scale wordpress_wordpress=2
  - sleep 30
  - docker ps
  - export CONTAINER_COUNT=`docker ps -q $1 | grep wordpress:php7.1-fpm-alpine | wc -l`
  - echo $CONTAINER_COUNT
  - if [[ "$CONTAINER_COUNT" == 2 ]]; then echo "OK"; else exit 1; fi

  # Remove the service
  - docker service rm wpdbcluster wordpress
